---
version: "2"
use_cases:
- name: default
  sections:
  - name: Compute
    groups:
    - name: VM Specs
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the VM."
        key: vm_instance_type
        widget: dropdown
        type: string
        default: "t3a.small"
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-ec2-instance-types.json
        required: true

      - name: "Disk size"
        unit: Go
        description: "Disk size for the VM."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 20
            - 250
        required: true

    - name: Day-2 Operations
      technologies: [pipeline]
      vars:
      - name: "Instance status"
        description: "Status for the deployed instances."
        key: vm_instance_status
        widget: radios
        type: string
        default: "Started"
        values:
            - "Started"
            - "Stopped"
        required: true

      - name: "Destroy Timer"
        description: "The number of minutes to wait before automatically destroying the infrastructure after creation."
        key: destroy_timer_in_minutes
        widget: number
        type: integer
        default: 60
        required: true
