---
version: "2"
use_cases:
- name: default
  sections:
  - name: Azure Function App
    groups:
    - name: Azure Function Platform
      technologies: [terraform]
      vars:
      - name: "Service plan SKU name"
        description: "The name of the SKU for the Service Plan."
        key: service_plan_sku_name
        widget: auto_complete
        type: string
        values: ["B1", "B2", "B3", "D1", "F1", "I1", "I2", "I3", "I1v2", "I2v2", "I3v2", "I4v2", "I5v2", "I6v2", "P1v2", "P2v2", "P3v2", "P0v3", "P1v3", "P2v3", "P3v3", "P1mv3", "P2mv3", "P3mv3", "P4mv3", "P5mv3", "S1", "S2", "S3", "SHARED", "EP1", "EP2", "EP3", "FC1", "WS1", "WS2", "WS3", "Y1"]
        default: "Y1"
        required: true

      - name: "Python Version"
        description: "The version of Python."
        key: python_version
        widget: auto_complete
        type: string
        values: ["3.8","3.9","3.10","3.11"]
        default: "3.11"
        required: true

      - name: "Create or Select Resource Group"
        description: "Whether to create a new Resource Group or select an existing one."
        key: res_selector
        widget: dropdown
        type: map
        required: true
        default: "Create new"
        values:
        - {"label": "Create new", "value": "create"}
        - {"label": "Select from Asset Inventory", "value": "inventory"}

    - name: Select from Asset Inventory
      technologies: [terraform]
      condition: '$res_selector == "Select from Asset Inventory"'
      vars:
      - name: "Existing Resource Group Name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: resource_group_name_inventory
        widget: cy_inventory_resource
        widget_config:
          attribute: name
          filters:
            type: azurerm_resource_group
        type: string
        required: true

    - name: Function Deployment
      technologies: [pipeline]
      vars:
      - name: "Function Git Repository URL"
        description: "Public git URL of the function to deploy."
        key: git_func_url
        widget: auto_complete
        type: string
        values: ["https://github.com/cycloid-community-catalog/onboarding-functions.git"]
        default: "https://github.com/cycloid-community-catalog/onboarding-functions.git"
        required: true

      - name: "Function Git Repository Branch"
        description: "Git Repository Branch of the function to deploy."
        key: git_func_branch
        widget: auto_complete
        type: string
        values: ["master","main","develop"]
        default: "master"
        required: true

    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true
