---
version: "2"
use_cases:
- name: default
  sections:
  - name: S3
    groups:
    - name: S3 Configuration
      technologies: [terraform]
      vars:
      - name: "Bucket Name"
        description: "Name of the S3 bucket to create"
        key: bucket_name
        widget: simple_text
        type: string
        required: true
        validations:
        - regexp: "^[a-z0-9][a-z0-9.-]*[a-z0-9]$"
          error_message: "Must be 3 to 63 alphanumeric, dots, and hyphens chars."
      - name: "Enable Website Hosting"
        description: "Enable website hosting for the bucket"
        key: bucket_enable_website_hosting
        widget: switch
        type: boolean
        default: true
        required: true
    - name: Website Hosting Configuration
      technologies: [terraform]
      condition: '$bucket_enable_website_hosting == true'
      vars:
      - name: "Index Document"
        description: "Index document for the bucket"
        key: bucket_index_document
        widget: simple_text
        type: string
        default: "index.html"
        required: true
      - name: "Error Document"
        description: "Error document for the bucket"
        key: bucket_error_document
        widget: simple_text
        type: string
        default: "error.html"
        required: true


    - name: AWS
      technologies: [pipeline]
      vars:
      - name: "AWS Account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true

      - name: "AWS Region"
        description: "AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        default: "eu-west-1"
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        required: true
