---
# Configuration of the Cycloid stack
version: '4'
name: 'AWS Landing Zone'
canonical: stack-network-aws
author: Cycloid
description: |
  Deploys a VPC with public and private subnets.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/aws-vpc.png
keywords:
  - network
  - vpc
  - subnet
  - provider:aws
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .config_root $)/terraform/main.tf'