---
version: "2"
use_cases:
- name: default
  sections:
  - name: AWS Network Landing Zone
    groups:
    - name: Network Configuration
      technologies: [terraform]
      vars:
      - name: "VPC CIDR"
        description: "The CIDR of the VPC to create."
        key: module.network.vpc_cidr
        widget: simple_text
        type: string
        default: "10.0.0.0/16"
        validations: 
        - regexp: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\/[0-9]{1,2}$" 
          error_message: "Please enter a valid CIDR such as 10.0.0.0/16"
        required: true
      - name: "Public Subnet CIDR"
        description: "The CIDR of the public subnet."
        key: module.network.vpc_public_subnet
        widget: simple_text
        type: string
        default: "10.0.0.0/24"
        validations: 
        - regexp: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\/[0-9]{1,2}$" 
          error_message: "Please enter a valid CIDR such as 10.0.0.0/24"
        required: true
      - name: "Private Subnet CIDR"
        description: "The CIDR of the private subnet."
        key: module.network.vpc_private_subnet
        widget: simple_text
        type: string
        default: "10.0.1.0/24"
        validations: 
        - regexp: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\/[0-9]{1,2}$" 
          error_message: "Please enter a valid CIDR such as 10.0.0.0/24"
        required: true
      - name: "NAT Gateway"
        description: "Whether to deploy a NAT gateway or not."
        key: module.network.nat_gateway
        widget: switch
        type: boolean
        default: false
        required: true
