resource_types:
- name: terraform
  type: registry-image
  source:
    repository: cycloid/terraform-resource
    tag: ((terraform_version))


resources:
- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ($ .env $)
    backend_type: http
    backend_config:
      address: '($ .api_url $)/inventory?jwt=($ .inventory_jwt $)'
    vars:
      cy_api_key: ((cy_api_key))
      cy_api_url: ($ .api_url $)
      cy_org: ($ .org $)
      cy_project: ($ .project $)
      cy_env: ($ .env $)
      cy_component: ($ .component $)
($ if eq .use_case "aws" $)
      aws_access_key: ($ .env_providers.aws.access_key $)
      aws_secret_key: ($ .env_providers.aws.secret_key $)
      aws_region: ($ .env_vars.aws_region $)
($ else if eq .use_case "azure" $)
      azure_client_id: ($ .env_providers.azurerm.client_id $)
      azure_client_secret: ($ .env_providers.azurerm.client_secret $)
      azure_tenant_id: ($ .env_providers.azurerm.tenant_id $)
      azure_subscription_id: ($ .env_providers.azurerm.subscription_id $)
($ else if eq .use_case "gcp" $)
      gcp_credentials_json: ($ .env_providers.google.json_key $)
      gcp_project: ($ .env_vars.gcp_project $)
      gcp_region: ($ .env_vars.gcp_region $)
      gcp_zone: ($ .env_vars.gcp_zone $)
    env:
      GOOGLE_PROJECT: ($ .env_vars.gcp_project $)
      GOOGLE_REGION: ($ .env_vars.gcp_region $)
      GOOGLE_ZONE: ($ .env_vars.gcp_zone $)
      GOOGLE_CREDENTIALS: ($ .env_providers.google.json_key $)
($ else if eq .use_case "clevercloud" $)
      clevercloud_token: ($ .env_providers.clevercloud.token $)
      clevercloud_secret: ($ .env_providers.clevercloud.secret $)
      clevercloud_organisation: ($ .env_providers.clevercloud.organisation $)
($ end $)


# The Terraform stack (will be merged with the config)
- name: git_stack-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .scs_url $)
    ($- if eq .stack_version_type "tag" $)
    tag_filter: ($ .stack_version_ref $)
    fetch_tags: true
    ($- else $)
    branch: ($ coalesce .stack_version_ref .catalog_repository_branch $)
    ($- end $)
    ($- if eq .scs_cred_type "basic_auth" $)
    username: ((($ .scs_cred_path $).username))
    password: ((($ .scs_cred_path $).password))
    ($- end $)
    ($- if eq .scs_cred_type "ssh" $)
    private_key: ((($ .scs_cred_path $).ssh_key))
    ($- end $)
    ($- if ne .stack_version_type "tag" $)
    paths:
      - ($ .stack_path $)/terraform/($ .use_case $)/*
    ($- end $)

# The Terraform config (will be merged with the stack)
- name: git_config-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .config_root $)/terraform/($ .use_case $)/*


groups:
- name: overview
  jobs:
    - deploy

- name: actions
  jobs:
    - snapshot
    - full-backup
    - restore

- name: destroy
  jobs:
    - destroy


jobs:
  - name: deploy
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: true
        - get: git_config-terraform
          trigger: true

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .config_root $)/terraform/($ .use_case $)
          STACK_PATH: ($ .stack_path $)/terraform/($ .use_case $)

      - put: tfstate
        params:
          terraform_source: merged-stack/

      - get: tfstate

      - task: register-plugins
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          inputs:
          - name: tfstate
            path: tfstate
          - name: git_stack-terraform
            path: stack
          run:
            path: stack/($ coalesce .stack_path "stack-postgresql" $)/pipeline/register-plugins.sh
        params:
          REGISTER_PLUGINS: '((register_plugins:true))'
          PLUGIN_REGISTRY: '((plugin_registry:""))'
          PLUGIN_ADMINER_NAME: '((plugin_adminer_name:Adminer))'
          PLUGIN_ADMINER_INSTALL_NAME: '((plugin_adminer_install_name:Adminer))'
          PLUGIN_ADMINER_VERSION_ID: '((plugin_adminer_version_id:""))'
          PLUGIN_PG_USERS_NAME: '((plugin_postgresql_users_name:"PostgreSQL Users"))'
          PLUGIN_PG_USERS_INSTALL_NAME: '((plugin_postgresql_users_install_name:"PostgreSQL Users"))'
          PLUGIN_PG_USERS_VERSION_ID: '((plugin_postgresql_users_version_id:""))'
          CY_API_KEY: ((cy_api_key))
          CY_API_URL: ($ .api_url $)
          CY_ORG: ($ .org $)
          CY_PROJECT: ($ .project $)
          CY_ENV: ($ .env $)
          CY_COMPONENT: ($ .component $)


  - name: snapshot
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - task: snapshot
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
          run:
            path: /bin/bash
            args:
              - '-ec'
              - |
                echo "Snapshotting database... Done"


  - name: full-backup
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - task: full-backup
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
          run:
            path: /bin/bash
            args:
              - '-ec'
              - |
                echo "Running full backup... Done"


  - name: restore
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - task: restore
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
          run:
            path: /bin/bash
            args:
              - '-ec'
              - |
                echo "Restoring database from backup... Done"


  - name: destroy
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: false
        - get: git_config-terraform
          trigger: false
        - get: tfstate
          trigger: true

      - task: timer-before-destroy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
          run:
            path: sleep
            args:
              - '((destroy_timer_in_minutes))m'

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .config_root $)/terraform/($ .use_case $)
          STACK_PATH: ($ .stack_path $)/terraform/($ .use_case $)

      - put: tfstate
        params:
          action: destroy
          terraform_source: merged-stack/
        get_params:
          action: destroy